###############################
# REST style 1, well supported
###############################

###
GET http://localhost:8080/api/v1/todos?userId2=userId2&text2=text2&done2=true

###
GET http://localhost:8080/api/v1/todos?ids=T9527&ids=T3916 589616287113937&userId2=1,2,33&text2=text2&done2=true&done2=false

###
POST http://localhost:8080/api/v1/todos
content-type: application/json

{"input": {"userID":"uid", "text":"$text"}}

###
PUT http://localhost:8080/api/v1/todo/T9527
content-type: application/json

{"input": {"userID":"uid", "text":"$text.Updated"}}

###
DELETE http://localhost:8080/api/v1/todo/T95270

### 
GET http://localhost:8080/api/v1/todos?ids=T9527&userId2=userId2&text2=text2&done2=true


###############################
# REST style 2, not supported yet
###############################

###
POST http://localhost:8080/api/v1/todos HTTP/1.1
content-type: application/json

{
    "userID":"uid",
    "text":"text",
    "done": false
}

###
POST http://localhost:8080/api/v1/todo/{id}/complete HTTP/1.1
content-type: application/json

{
    "userID":"uid",
    "text":"text",
    "done": false
}

###
POST http://localhost:8080/api/v1/todos/bulk-complete HTTP/1.1
content-type: application/json

{
    "ids":["T9527","xx"]
}

###
# PUT http://localhost:8080/api/v1/todos/T9527?verbose=true&lang=zh-CN HTTP/1.1
PUT http://localhost:8080/api/v1/todo/T9527
content-type: application/json

{
    "userID":"uid0", 
    "text":"textPUT"
}

###
GET http://localhost:8080/api/v1/todos?ids=1,2,3,4&ids=5,6

###
GET http://localhost:8080/api/v1/non-exist?ids=1,2,3,4&ids=5,6

###
DELETE http://localhost:8080/api/v1/todos/uid0




###
GET http://localhost:8080/api/v1/overlapping