// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userID"`
	Done   *bool  `json:"done"`
}

type UpdateTodoInput struct {
	ID     string  `json:"id"`
	Text   *string `json:"text"`
	UserID *string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role Role   `json:"role"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TodoType string

const (
	TodoTypeTypeA TodoType = "TypeA"
	TodoTypeTypeB TodoType = "TypeB"
)

var AllTodoType = []TodoType{
	TodoTypeTypeA,
	TodoTypeTypeB,
}

func (e TodoType) IsValid() bool {
	switch e {
	case TodoTypeTypeA, TodoTypeTypeB:
		return true
	}
	return false
}

func (e TodoType) String() string {
	return string(e)
}

func (e *TodoType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoType", str)
	}
	return nil
}

func (e TodoType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
